#!/bin/tcsh

rm -r MacroAnXfZip*




set ebinlows = "18 23 28 33 38 43 48 53 58 65 "
set ebinhighs = "23 28 33 38  43 48 53 58 65 75 "
set nebins = 10

set elowlist = ($ebinlows)
set ehighlist = ($ebinhighs)

set mbinlows = " 0.00  0.20 "
set mbinhighs = " 0.20  0.30"
set nmbins = 2
set mlowlist = ($mbinlows)
set mhighlist = ($mbinhighs)


set mcnt = 1
while( $mcnt <= $nmbins )
set mlow = $mlowlist[$mcnt]
set mhigh = $mhighlist[$mcnt]
	set cnt = 1
	while( $cnt <= $nebins )
		set elow = $elowlist[$cnt]
		set ehigh = $ehighlist[$cnt]
	  	star-submit-template -template xmlAn.xml -entities Elow=$elow,Ehigh=$ehigh,Mlow=$mlow,Mhigh=$mhigh,
		@ cnt += 1
	end
@ mcnt += 1
end

echo "done"
